events {}

stream {
    map $ssl_server_name $backend {
        server-a server-a-backend:6167;
        server-b server-b-backend:6167;
    }

    server {
        listen 6167 ssl;
        ssl_certificate /certs/server-a.crt;
        ssl_certificate_key /certs/server-a.key;
        proxy_pass server-a-backend:6167;
    }

    server {
        listen 8448 ssl;
        ssl_certificate /certs/server-a.crt;
        ssl_certificate_key /certs/server-a.key;
        proxy_pass server-a-backend:6167;
    }
}

http {
    server {
        listen 6170;
        location / { proxy_pass http://server-a-backend:6167; }
    }
    server {
        listen 6171;
        location / { proxy_pass http://server-b-backend:6167; }
    }
}
