events {}
stream {
    server {
        listen 8448 ssl;
        listen 6167 ssl;
        ssl_certificate /certs/server-a.crt;
        ssl_certificate_key /certs/server-a.key;
        proxy_pass server-a-backend:6167;
    }
}
http {
    server {
        listen 80;
        location / { proxy_pass http://server-a-backend:6167; }
    }
}
