events {}
stream {
    server {
        listen 8448 ssl;
        listen 6167 ssl;
        ssl_certificate /certs/server-b.crt;
        ssl_certificate_key /certs/server-b.key;
        proxy_pass server-b-backend:6167;
    }
}
http {
    server {
        listen 80;
        location / { proxy_pass http://server-b-backend:6167; }
    }
}
